#!/bin/sh
echo Concatenating hosts...
python3 hosts_concat.py sources.txt
adb root
echo Pulling old hosts files...
adb pull /system/etc/hosts old_hosts
echo Pushing new hosts file...
adb push hosts /system/etc
